
bot:
  token: vk1.a.2QX30vzXv86Yge4oS5MeibmPBlT0gSFRkZ2_AUIIOTUjDxbJys6JL9b_1zuX-1QOs6njHGYz-j9UXXf4rxFkQFqOl5jRuNl5hAx2CAMS4Fcbep0eIU1gnfOot91wYbUkc1wiw6vl90T71gx0NzUVqRS3UEPTy_pQgqSfxcFXsOtykgeYDYJTTC03zzKmYcrr_qcAz_YauFYw0jWVS30FZA
  group_id: 207946988


