"""empty message

Revision ID: af9f3a08a2fe
Revises: 02d03f3e7912
Create Date: 2023-03-13 19:55:17.806925

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'af9f3a08a2fe'
down_revision = '02d03f3e7912'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
