"""Add GameModel

Revision ID: eb47d650c4bf
Revises: e0fb8c912758
Create Date: 2023-03-07 21:26:04.620744

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eb47d650c4bf'
down_revision = 'e0fb8c912758'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('kicked_users', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'kicked_users')
    # ### end Alembic commands ###
